### ISSUE TITLE
Example output

### ISSUE THREAD

**Issue by o-william-white** [BiodivGenomic/ECuADOR#1]
Hello, 

Thanks for sharing this software, looks really useful.

I was just having a go at replicating the example output but it look the orientated output files are missing. 

I ran the example as below:
`perl ../ECuADOR.pl -i 5cpDNAtest -w 1000 -f fasta -out test --ext fasta --save_regions ALL --orient TRUE --noIRs 2`

I get output files called "cpDNA_fasta_ext_test" and "cpDNA_regions_test" as expected. 

While I do get an output folder called "TcpDNA_oriented_test" the file within it "Oriented_test.IRA.fasta" is empty. In addition there is no output file called "TcpDNA_oriented_all".

I haven't got any warnings suggesting that I need further perl modules so I think my installation is ok. 

If you have any suggestions please do let me know, 

Best wishes
Ollie

**Comment by BiodivGenomic** [comment]
Hello, Ollie, thanks to making us know about this issue and we are very sorry for our late reply, what version of ECuADOR do you use ? It could be an issue related to the v1, a v2 have been released, you only need to go to the release section in the page (https://github.com/BiodivGenomic/ECuADOR/releases) and download the latest version of the script and replace the old version with the newly downloaded one. It should fix this issue.
Let us know if it solved your issue...
